# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SalesTaxesModule' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SalesTaxesModule

  pod 'JSONModel'
  pod 'Masonry'
  pod 'HMSegmentedControl'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'

end
